###############################################################################
# power_quarantine_helpers.r
#
# E005/E006 guardrail: Cox power rows generated by the current row-level
# simsurv DGP are diagnostic only. They do not preserve the fitted
# counting-process risk-set geometry, so they must not remain in citation-ready
# H1/H2.1 power summaries until a campaign-history simulator is implemented.
###############################################################################

cox_power_quarantine_specs <- function(results_dir,
                                       calibration_file = "power_cox_specs_calibration.csv") {
  quarantine <- data.frame(
    order = 1:3,
    summary_family = c("h1", "h21", "h21"),
    family = c("H1", "H2.1", "H2.1"),
    spec = c("M4", "M7", "M8"),
    quarantine_reason = "invalid_counting_process_dgp",
    cox_power_citable = FALSE,
    stringsAsFactors = FALSE
  )

  calibration_path <- file.path(results_dir, calibration_file)
  if (!file.exists(calibration_path) &&
      calibration_file != "power_cox_specs_calibration.csv") {
    calibration_path <- file.path(results_dir, "power_cox_specs_calibration.csv")
  }
  if (file.exists(calibration_path)) {
    calibration <- read.csv(calibration_path, stringsAsFactors = FALSE)
    calibration_keep <- intersect(
      c(
        "family", "spec", "type1_at_null_05", "fit_ok_rate_min",
        "type1_inflated_warning", "cox_calibration_status"
      ),
      names(calibration)
    )
    quarantine <- merge(
      quarantine,
      calibration[, calibration_keep, drop = FALSE],
      by = c("family", "spec"),
      all.x = TRUE,
      sort = FALSE
    )
    quarantine <- quarantine[order(quarantine$order), , drop = FALSE]
  }

  quarantine$order <- NULL
  quarantine
}

first_value <- function(dat, col, default = NA) {
  if (!col %in% names(dat) || nrow(dat) == 0L) return(default)
  dat[[col]][1]
}

make_cox_quarantine_audit <- function(removed, summary_family, source_file, results_dir) {
  if (nrow(removed) == 0L) return(data.frame())

  calibration_file <- if (grepl("_smoke", source_file, fixed = TRUE)) {
    "power_cox_specs_smoke_calibration.csv"
  } else {
    "power_cox_specs_calibration.csv"
  }
  quarantine <- cox_power_quarantine_specs(results_dir, calibration_file)
  quarantine <- quarantine[quarantine$summary_family == summary_family, , drop = FALSE]

  audit_rows <- lapply(unique(removed$spec), function(sp) {
    removed_sp <- removed[removed$spec == sp, , drop = FALSE]
    q_sp <- quarantine[quarantine$spec == sp, , drop = FALSE]
    data.frame(
      source_file = source_file,
      family = first_value(q_sp, "family", default = summary_family),
      spec = sp,
      rows_removed = nrow(removed_sp),
      estimator = first_value(removed_sp, "estimator", default = NA_character_),
      moderator = first_value(removed_sp, "moderator", default = NA_character_),
      type1_at_null_05 = first_value(removed_sp, "type1_at_null_05", default = NA_real_),
      raw_power_at_fitted_05 = first_value(removed_sp, "raw_power_at_fitted_05", default = NA_real_),
      fit_ok_rate_min = first_value(removed_sp, "fit_ok_rate_min", default = NA_real_),
      cox_calibration_status = first_value(q_sp, "cox_calibration_status", default = NA_character_),
      quarantine_reason = first_value(q_sp, "quarantine_reason", default = "invalid_counting_process_dgp"),
      cox_power_citable = FALSE,
      stringsAsFactors = FALSE
    )
  })

  do.call(rbind, audit_rows)
}

filter_cox_power_quarantine <- function(dat, summary_family, source_file, results_dir) {
  if (!"spec" %in% names(dat)) {
    stop(sprintf("%s is missing required `spec` column", source_file), call. = FALSE)
  }

  quarantine <- cox_power_quarantine_specs(results_dir)
  quarantine_specs <- quarantine$spec[quarantine$summary_family == summary_family]
  remove_idx <- dat$spec %in% quarantine_specs
  removed <- dat[remove_idx, , drop = FALSE]

  list(
    data = dat[!remove_idx, , drop = FALSE],
    audit = make_cox_quarantine_audit(removed, summary_family, source_file, results_dir)
  )
}

write_cox_quarantine_audit <- function(audit_rows, results_dir) {
  audit_rows <- audit_rows[vapply(audit_rows, nrow, integer(1)) > 0L]
  if (length(audit_rows) == 0L) return(invisible(NULL))

  audit <- do.call(rbind, audit_rows)
  audit_path <- file.path(results_dir, "cox_power_quarantine_audit.csv")
  if (file.exists(audit_path)) {
    existing <- read.csv(audit_path, stringsAsFactors = FALSE)
    all_cols <- union(names(existing), names(audit))
    for (col in setdiff(all_cols, names(existing))) existing[[col]] <- NA
    for (col in setdiff(all_cols, names(audit))) audit[[col]] <- NA
    existing <- existing[, all_cols, drop = FALSE]
    audit <- audit[, all_cols, drop = FALSE]
    key_cols <- intersect(c("source_file", "family", "spec"), all_cols)
    if (length(key_cols) == 3L) {
      existing_key <- do.call(paste, c(existing[key_cols], sep = "\r"))
      audit_key <- do.call(paste, c(audit[key_cols], sep = "\r"))
      existing <- existing[!existing_key %in% audit_key, , drop = FALSE]
    }
    audit <- unique(rbind(existing, audit))
  }

  write.csv(audit, audit_path, row.names = FALSE)
  cat(sprintf("  Cox power quarantine audit written to %s (%d rows)\n", basename(audit_path), nrow(audit)))
  invisible(audit)
}

###############################################################################
# E007 guardrail: H2.2/H3 Weibull AFT power rows are nominal-Wald diagnostics.
# The bootstrap calibration sidecar shows that nominal survreg Wald inference is
# anti-conservative in these small samples. Keep the original values as
# diagnostics, but mark them as not size-calibrated citation-ready power/MDE.
###############################################################################

weibull_power_diagnostic_specs <- function(results_dir) {
  calibration_path <- file.path(results_dir, "weibull_bootstrap_calibration.csv")
  if (!file.exists(calibration_path)) {
    stop(sprintf("Missing Weibull calibration file: %s", calibration_path), call. = FALSE)
  }

  calibration <- read.csv(calibration_path, stringsAsFactors = FALSE)
  required <- c(
    "family", "spec", "moderator", "z_critical_emp_05",
    "z_critical_holm", "empirical_alpha_at_nominal_z196",
    "p_calibrated_emp", "fit_ok_rate"
  )
  missing <- setdiff(required, names(calibration))
  if (length(missing) > 0L) {
    stop(sprintf(
      "Weibull calibration file is missing columns: %s",
      paste(missing, collapse = ", ")
    ), call. = FALSE)
  }

  calibration <- calibration[
    calibration$family %in% c("H2.2", "H3") &
      calibration$spec %in% paste0("M", 1:4),
    ,
    drop = FALSE
  ]
  calibration$summary_family <- ifelse(calibration$family == "H2.2", "h22", "h3")
  calibration$weibull_power_citable <- FALSE
  calibration$weibull_power_status <- "nominal_wald_diagnostic_not_size_calibrated"
  calibration$weibull_calibration_source <- basename(calibration_path)
  calibration$weibull_power_note <- paste(
    "Nominal survreg Wald power/MDE diagnostic; bootstrap calibration shows",
    "anti-conservative size, so this row is not size-calibrated citation-ready power."
  )
  calibration
}

weibull_summary_metric <- function(dat, metric, default = NA_real_) {
  if (metric %in% names(dat)) return(dat[[metric]][1])
  if (!all(c("magnitude", "alpha", "raw_power", "holm_proxy_power") %in% names(dat))) {
    return(default)
  }
  if (metric == "type1_at_null_05") {
    hit <- dat[dat$magnitude == 0 & dat$alpha == 0.05, , drop = FALSE]
    if (nrow(hit) > 0L) return(hit$raw_power[1])
  }
  if (metric == "raw_power_at_fitted_05") {
    hit <- dat[dat$magnitude == 1 & dat$alpha == 0.05, , drop = FALSE]
    if (nrow(hit) > 0L) return(hit$raw_power[1])
  }
  default
}

make_weibull_diagnostic_audit <- function(annotated, summary_family, source_file, results_dir) {
  if (nrow(annotated) == 0L) return(data.frame())

  specs <- weibull_power_diagnostic_specs(results_dir)
  specs <- specs[specs$summary_family == summary_family, , drop = FALSE]

  audit_rows <- lapply(unique(annotated$spec), function(sp) {
    sp_rows <- annotated[annotated$spec == sp, , drop = FALSE]
    sp_cal <- specs[specs$spec == sp, , drop = FALSE]
    data.frame(
      source_file = source_file,
      family = first_value(sp_cal, "family", default = summary_family),
      spec = sp,
      rows_annotated = nrow(sp_rows),
      estimator = first_value(sp_rows, "estimator", default = NA_character_),
      moderator = first_value(sp_rows, "moderator", default = NA_character_),
      type1_at_null_05 = weibull_summary_metric(sp_rows, "type1_at_null_05"),
      raw_power_at_fitted_05 = weibull_summary_metric(sp_rows, "raw_power_at_fitted_05"),
      empirical_alpha_at_nominal_z196 = first_value(
        sp_cal, "empirical_alpha_at_nominal_z196", default = NA_real_
      ),
      z_critical_emp_05 = first_value(sp_cal, "z_critical_emp_05", default = NA_real_),
      z_critical_holm = first_value(sp_cal, "z_critical_holm", default = NA_real_),
      p_calibrated_emp = first_value(sp_cal, "p_calibrated_emp", default = NA_real_),
      diagnostic_reason = "nominal_wald_anti_conservative_bootstrap_calibration",
      weibull_power_citable = FALSE,
      stringsAsFactors = FALSE
    )
  })

  do.call(rbind, audit_rows)
}

annotate_weibull_power_diagnostics <- function(dat, summary_family, source_file, results_dir) {
  if (nrow(dat) == 0L || !summary_family %in% c("h22", "h3")) {
    return(list(data = dat, audit = data.frame()))
  }
  if (!all(c("spec", "estimator") %in% names(dat))) {
    stop(sprintf("%s is missing required `spec` or `estimator` column", source_file), call. = FALSE)
  }

  specs <- weibull_power_diagnostic_specs(results_dir)
  specs <- specs[specs$summary_family == summary_family, , drop = FALSE]
  key <- paste(specs$family, specs$spec)

  annotation_cols <- c(
    "weibull_power_citable", "weibull_power_status",
    "weibull_calibration_source", "weibull_empirical_alpha_nominal_05",
    "weibull_z_critical_emp_05", "weibull_z_critical_holm",
    "weibull_p_calibrated_observed", "weibull_calibration_fit_ok_rate",
    "weibull_power_note"
  )
  for (col in annotation_cols) {
    if (!col %in% names(dat)) dat[[col]] <- NA
  }

  family_label <- ifelse(summary_family == "h22", "H2.2", "H3")
  idx <- dat$estimator == "Weibull AFT" & dat$spec %in% specs$spec

  for (i in which(idx)) {
    sp_key <- paste(family_label, dat$spec[i])
    cal <- specs[key == sp_key, , drop = FALSE]
    if (nrow(cal) != 1L) {
      stop(sprintf("Missing Weibull calibration row for %s", sp_key), call. = FALSE)
    }
    dat$weibull_power_citable[i] <- FALSE
    dat$weibull_power_status[i] <- cal$weibull_power_status[1]
    dat$weibull_calibration_source[i] <- cal$weibull_calibration_source[1]
    dat$weibull_empirical_alpha_nominal_05[i] <- cal$empirical_alpha_at_nominal_z196[1]
    dat$weibull_z_critical_emp_05[i] <- cal$z_critical_emp_05[1]
    dat$weibull_z_critical_holm[i] <- cal$z_critical_holm[1]
    dat$weibull_p_calibrated_observed[i] <- cal$p_calibrated_emp[1]
    dat$weibull_calibration_fit_ok_rate[i] <- cal$fit_ok_rate[1]
    dat$weibull_power_note[i] <- cal$weibull_power_note[1]
  }

  annotated <- dat[idx, , drop = FALSE]
  list(
    data = dat,
    audit = make_weibull_diagnostic_audit(annotated, summary_family, source_file, results_dir)
  )
}

write_weibull_diagnostic_audit <- function(audit_rows, results_dir) {
  audit_rows <- audit_rows[vapply(audit_rows, nrow, integer(1)) > 0L]
  if (length(audit_rows) == 0L) return(invisible(NULL))

  audit <- do.call(rbind, audit_rows)
  audit_path <- file.path(results_dir, "weibull_power_diagnostic_audit.csv")
  if (file.exists(audit_path)) {
    existing <- read.csv(audit_path, stringsAsFactors = FALSE)
    all_cols <- union(names(existing), names(audit))
    for (col in setdiff(all_cols, names(existing))) existing[[col]] <- NA
    for (col in setdiff(all_cols, names(audit))) audit[[col]] <- NA
    existing <- existing[, all_cols, drop = FALSE]
    audit <- audit[, all_cols, drop = FALSE]
    key_cols <- intersect(c("source_file", "family", "spec"), all_cols)
    if (length(key_cols) == 3L) {
      existing_key <- do.call(paste, c(existing[key_cols], sep = "\r"))
      audit_key <- do.call(paste, c(audit[key_cols], sep = "\r"))
      existing <- existing[!existing_key %in% audit_key, , drop = FALSE]
    }
    audit <- unique(rbind(existing, audit))
  }

  write.csv(audit, audit_path, row.names = FALSE)
  cat(sprintf(
    "  Weibull diagnostic audit written to %s (%d rows)\n",
    basename(audit_path), nrow(audit)
  ))
  invisible(audit)
}
