# Fit the ten accepted C23 sensemakr linear-probability analogs.
.root <- Sys.getenv("REPLICATION_ROOT", unset=""); if(!nzchar(.root)){.a<-grep("^--file=",commandArgs(FALSE),value=TRUE);.root<-file.path(dirname(normalizePath(sub("^--file=","",.a[1]))),"..","..")}
source(file.path(.root,"code","R","_table_helpers.R"));P<-replication_bootstrap();source(file.path(P$code,"_robustness_helpers.R"));suppressPackageStartupMessages(library(sensemakr));df<-prepare_robustness_data(P)$df
specs<-list(
 list("H2.1_domaut","H2.1 Political","domaut","domaut_c","nonviolent_camp+REGCHANGE+v2csreprss+lnlengthofcam+lnnum_image_sum",c("v2csreprss","REGCHANGE")),list("H2.1_stterr","H2.1 Political","stterr","stterr_c","nonviolent_camp+REGCHANGE+v2csreprss+lnlengthofcam+lnnum_image_sum",c("v2csreprss","REGCHANGE")),
 list("H2.2_FDI","H2.2 Economic","FDI","fdiin_c","nonviolent_camp+goals+v2csreprss+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),list("H2.2_Trade","H2.2 Economic","Trade","trade_c","nonviolent_camp+goals+v2csreprss+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),
 list("H2.2_Aid","H2.2 Economic","Aid","lnaid_c","nonviolent_camp+REGCHANGE+v2csreprss+lngdp+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),list("H2.2_IODonor","H2.2 Economic","IODonor","iodonor_c","nonviolent_camp+REGCHANGE+v2csreprss+lngdp+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),
 list("H3_Repress","H3 Domestic","Repress","repress_c","nonviolent_camp+goals+p_polity2+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("p_polity2","lngdp")),list("H3_CivLib","H3 Domestic","CivLib","civlib_c","nonviolent_camp+goals+v2csreprss+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),list("H3_Clpol","H3 Domestic","Political Liberty","clpol_c","nonviolent_camp+goals+v2csreprss+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")),list("H3_Polity","H3 Domestic","Polity","polity_c","nonviolent_camp+goals+v2csreprss+lngdp+lnpop+colonized_english+lnlengthofcam+lnnum_image_sum",c("v2csreprss","lngdp")))
fits<-list();rows<-lapply(specs,function(s){f<-as.formula(paste("concession_bin~eng_c*",s[[4]],"+",s[[5]]));m<-lm(f,data=df,na.action=na.omit);tr<-paste0("eng_c:",s[[4]]);sm<-sensemakr(m,treatment=tr,benchmark_covariates=s[[6]],kd=1,ky=1,q=1,alpha=.05);fits[[s[[1]]]]<<-list(lpm=m,sensemakr=sm);ct<-summary(m)$coefficients;bb<-sm$bounds;data.frame(model=s[[1]],family=s[[2]],moderator=s[[3]],estimator="LPM + sensemakr",treatment=tr,estimate=ct[tr,"Estimate"],se=ct[tr,"Std. Error"],p=ct[tr,"Pr(>|t|)"],rv_q1=sm$sensitivity_stats$rv_q,rv_qa1=sm$sensitivity_stats$rv_qa,benchmark=if(nrow(bb))rownames(bb)[1]else NA,bench1_r2y=if(nrow(bb))bb[1,"r2yz.dx"]else NA,bench1_r2d=if(nrow(bb))bb[1,"r2dz.x"]else NA,bench1_adjusted_estimate=if(nrow(bb))bb[1,"adjusted_estimate"]else NA,N=nobs(m),stringsAsFactors=FALSE)})
out<-dplyr::bind_rows(rows);if(nrow(out)!=10L)stop("C23 must contain ten rows.",call.=FALSE);write.csv(out,file.path(P$estimates,"appendix_sensemakr_bounds_results.csv"),row.names=FALSE,na="");saveRDS(fits,file.path(P$cache,"sensemakr_models.rds"))
