# Rebuild Appendix C1-C6 from fresh H1/H2.1 model caches.
.root<-Sys.getenv("REPLICATION_ROOT",unset="");if(!nzchar(.root)){.a<-grep("^--file=",commandArgs(FALSE),value=TRUE);.root<-file.path(dirname(normalizePath(sub("^--file=","",.a[1]))),"..","..")};source(file.path(.root,"code","R","_table_helpers.R"));P<-replication_bootstrap()
spec<-function(n)file.path(P$code,"specs","appendix",n); out<-function(n)file.path(P$appendix_tables,n)
h1<-read_models(P,"H1");h1s<-read.csv(file.path(P$estimates,"H1_curvilinear_results.csv"))
write_body(hydrate_scaffold(spec("H1_strict_success_appendix_table_body.csv"),h1[c("M1s","M2s","M3","M4s","M5s","M6")],h1s),out("H1_strict_success_appendix_table_body.csv"),29L)
write_body(hydrate_scaffold(spec("H1_sensitivity_appendix_table_body.csv"),h1[c("M1_ln","M1_cox","M4_AG","M5_GEE")],h1s),out("H1_sensitivity_appendix_table_body.csv"),27L)
h21<-read_models(P,"H21");ext<-read_models(P,"H21_extensions");h21s<-read.csv(file.path(P$estimates,"H21_results.csv"));qs<-read.csv(file.path(P$estimates,"H21_curvilinear_appendix_results.csv"));ls<-read.csv(file.path(P$estimates,"H21_limited_success_results.csv"))
write_body(hydrate_scaffold(spec("H21_curvi_appendix_table_body.csv"),ext[c("M1q","M2q","M3q","M4q","M7q","M8q","M9q","M10q")],qs),out("H21_curvi_appendix_table_body.csv"),35L)
write_body(hydrate_scaffold(spec("H21_strict_success_table_body.csv"),h21[c("M1s","M2s","M3s","M4s","M7s","M8s","M9s","M10s")],h21s),out("H21_strict_success_table_body.csv"),29L)
write_body(hydrate_scaffold(spec("H21_strict_success_table_body.csv"),ext[c("M1l","M2l","M3l","M4l","M7l","M8l","M9l","M10l")],ls),out("H21_limited_success_table_body.csv"),29L)
write_body(hydrate_scaffold(spec("H21_rest_appendix_table_body.csv"),h21[c("M5","M6","M11","M12","M7_AG","M8_AG","M9_GEE","M10_GEE")],h21s),out("H21_rest_appendix_table_body.csv"),29L)
