# Rebuild accepted general robustness Tables C21-C24.
.root<-Sys.getenv("REPLICATION_ROOT",unset="");if(!nzchar(.root)){.a<-grep("^--file=",commandArgs(FALSE),value=TRUE);.root<-file.path(dirname(normalizePath(sub("^--file=","",.a[1]))),"..","..")};source(file.path(.root,"code","R","_table_helpers.R"));P<-replication_bootstrap()
read_est<-function(n)read.csv(require_file(file.path(P$estimates,n)),stringsAsFactors=FALSE);out<-function(n)file.path(P$appendix_tables,n)
col_na<-function(d,n)if(n%in%names(d))d[[n]]else rep(NA,nrow(d));adj_p<-function(raw,holm,bh,main){main<-!is.na(main)&as.logical(main);ifelse(main&!is.na(holm),holm,ifelse(!main&!is.na(bh),bh,raw))};adj_lab<-function(holm,bh,main){main<-!is.na(main)&as.logical(main);ifelse(main&!is.na(holm),"Holm",ifelse(!main&!is.na(bh),"BH","Raw"))}
h1<-read_est("H1_curvilinear_results.csv");h21<-read_est("H21_results.csv");h22<-read_est("H22_results.csv");h3<-read_est("H3_results.csv")
strict<-function(x,f){z<-x[grepl("strict",x$response,ignore.case=TRUE),];z$Family<-f;z}
z1<-strict(h1,"H1");main1<-rep(FALSE,nrow(z1));a<-data.frame(Family=z1$Family,Model=z1$model,Estimator=z1$estimator,Dataset=z1$data,DV=z1$response,Moderator="English share squared",Beta=z1$beta_eng2,p=adj_p(z1$p_eng2,z1$p_eng2_holm,z1$p_eng2_bh,main1),Correction=adj_lab(z1$p_eng2_holm,z1$p_eng2_bh,main1),N=z1$N)
zi<-dplyr::bind_rows(strict(h21,"H2.1"),strict(h22,"H2.2"),strict(h3,"H3"));mi<-col_na(zi,"main_panel");b<-data.frame(Family=zi$Family,Model=zi$model,Estimator=zi$estimator,Dataset=zi$data,DV=zi$response,Moderator=zi$moderator,Beta=zi$beta_int,p=adj_p(zi$p_int,col_na(zi,"p_int_holm"),col_na(zi,"p_int_bh"),mi),Correction=adj_lab(col_na(zi,"p_int_holm"),col_na(zi,"p_int_bh"),mi),N=zi$N)
c21<-dplyr::bind_rows(a,b);c21<-data.frame(Family=c21$Family,Model=c21$Model,Estimator=c21$Estimator,Dataset=c21$Dataset,DV=c21$DV,Moderator=c21$Moderator,Beta=sprintf("%.3f",c21$Beta),`Adjusted p`=sprintf("%.3f",c21$p),Correction=c21$Correction,N=as.character(c21$N),check.names=FALSE);write_body(c21,out("appendix_A2_success_dv_table_body.csv"),44L)

nv<-read_est("appendix_nonviolent_subsample_results.csv");focal<-nv[(!is.na(nv$Variable)&nv$Variable=="I(eng_c^2)")|(!is.na(nv$Variable)&grepl(":",nv$Variable,fixed=TRUE)),]
if(sum(focal$Model=="NVH1"&focal$Variable=="I(eng_c^2)",na.rm=TRUE)!=1L)stop("Accepted C22 contract requires exactly one NVH1 focal row.",call.=FALSE)
num<-suppressWarnings(as.integer(sub("^NV([0-9]+).*","\\1",focal$Model)));family<-ifelse(focal$Model=="NVH1","Curvilinear",ifelse(num<=4,"Political",ifelse(num<=12,"Economic","Domestic")));mod<-ifelse(focal$Model=="NVH1","English share squared",focal$Moderator);status<-ifelse(is.na(focal$Fit_Status)|!nzchar(focal$Fit_Status),"reported",focal$Fit_Status)
c22<-data.frame(Family=family,Model=focal$Model,Estimator=focal$Estimator,Dataset=focal$DV,Moderator=mod,Beta=fmt_num(focal$Estimate),SE=fmt_num(focal$SE),p=ifelse(is.na(focal$p),"",sprintf("%.3f",focal$p)),`95% CI`=fmt_ci(focal$CI_lo,focal$CI_hi),N=as.character(focal$N),Status=status,check.names=FALSE)
ord<-c("NVH1","NV1","NV2","NV3","NV3_GEE","NV4","NV4_GEE","NV5","NV9","NV9_GEE","NV6","NV10","NV10_GEE","NV7","NV11","NV11_GEE","NV8","NV12","NV12_GEE","NV13","NV17","NV17_GEE","NV14","NV18","NV18_GEE","NV15","NV19","NV19_GEE","NV16","NV20","NV20_GEE");c22<-c22[match(ord,c22$Model),];if(any(is.na(c22$Model))||anyDuplicated(c22$Model))stop("C22 focal extraction/order failure.",call.=FALSE);write_body(c22,out("C22_nonviolent_final_body.csv"),31L)

sm<-read_est("appendix_sensemakr_bounds_results.csv");assessment<-ifelse(sm$rv_q1>=.30,"Robust",ifelse(sm$rv_q1>=.15,"Moderate",ifelse(sm$rv_q1>=.05,"Weak","Fragile")));c23<-data.frame(Family=sm$family,Moderator=sm$moderator,`Beta (LPM)`=sprintf("%.3f",sm$estimate),SE=sprintf("%.3f",sm$se),p=sprintf("%.3f",sm$p),RV=sprintf("%.3f",sm$rv_q1),`RV alpha`=ifelse(is.na(sm$rv_qa1)|sm$rv_qa1==0,"---",sprintf("%.3f",sm$rv_qa1)),`Bench R2y`=sprintf("%.3f",sm$bench1_r2y),`Bench R2d`=sprintf("%.3f",sm$bench1_r2d),`Adj. beta`=sprintf("%.3f",sm$bench1_adjusted_estimate),N=as.character(sm$N),Assessment=assessment,check.names=FALSE);write_body(c23,out("appendix_A4_sensemakr_bounds_table_body.csv"),10L)

og<-read_est("appendix_ongoing_sensitivity_results.csv");terms<-c(S1="eng_c:fdiin_c",S2="eng_c:trade_c",S3="eng_c:lnaid_c",S4="eng_c:iodonor_c",S5="eng_c:fdiin_c",S6="eng_c:trade_c",S7="eng_c:lnaid_c",S8="eng_c:iodonor_c");og<-og[og$Model%in%names(terms)&og$Variable==unname(terms[og$Model]),];og<-og[match(names(terms),og$Model),];if(any(is.na(og$Model))||anyDuplicated(og$Model))stop("C24 focal extraction failure.",call.=FALSE)
c24<-data.frame(Model=og$Model,Path=ifelse(og$Model%in%paste0("S",1:4),"B: Firth (resolved)","C: bracl (ongoing=limited)"),Estimator=og$Estimator,DV=og$DV,Moderator=og$Moderator,`Focal term`=og$Variable,Beta=mapply(fmt_coef,og$Estimate,og$p),SE=fmt_num(og$SE),p=sprintf("%.3f",og$p),`95% CI`=fmt_ci(og$CI_lo,og$CI_hi),N=as.character(og$N),check.names=FALSE);write_body(c24,out("appendix_A5_ongoing_sensitivity_table_body.csv"),8L)
